"""Banco inicial

Revision ID: 6c5a01b58d40
Revises: 
Create Date: 2024-12-04 20:57:38.755598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5a01b58d40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cli',
    sa.Column('cli_id', sa.Integer(), nullable=False),
    sa.Column('cli_nome', sa.VARCHAR(length=250), nullable=False),
    sa.Column('cli_tipo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('cli_status', sa.VARCHAR(length=1), nullable=True),
    sa.Column('cli_user_id_cad', sa.Integer(), nullable=False),
    sa.Column('cli_dthr_cad', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cli_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.VARCHAR(length=250), nullable=False),
    sa.Column('user_nome', sa.VARCHAR(length=250), nullable=False),
    sa.Column('user_senha', sa.VARCHAR(length=250), nullable=False),
    sa.Column('user_tipo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('user_user_id_cad', sa.Integer(), nullable=True),
    sa.Column('user_dthr_cad', sa.DateTime(), nullable=True),
    sa.Column('user_status', sa.VARCHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_login'),
    sa.UniqueConstraint('user_login', name='user_login_uniq')
    )
    op.create_table('ccr',
    sa.Column('ccr_id', sa.Integer(), nullable=False),
    sa.Column('ccr_saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ccr_dthr_ini', sa.DateTime(), nullable=True),
    sa.Column('ccr_tipo', sa.VARCHAR(length=2), nullable=False),
    sa.Column('ccr_cli_id', sa.Integer(), nullable=False),
    sa.Column('ccr_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ccr_cli_id'], ['cli.cli_id'], ),
    sa.ForeignKeyConstraint(['ccr_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('ccr_id')
    )
    op.create_table('mcc',
    sa.Column('mcc_id', sa.Integer(), nullable=False),
    sa.Column('mcc_valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mcc_dthr', sa.DateTime(), nullable=True),
    sa.Column('mcc_tipo', sa.VARCHAR(length=1), nullable=False),
    sa.Column('mcc_ccr_id', sa.Integer(), nullable=False),
    sa.Column('mcc_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mcc_ccr_id'], ['ccr.ccr_id'], ),
    sa.ForeignKeyConstraint(['mcc_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('mcc_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcc')
    op.drop_table('ccr')
    op.drop_table('user')
    op.drop_table('cli')
    # ### end Alembic commands ###
